const fs = require("fs");
const path = require("path");

const root = __dirname;

function writeFile(name, lines) {
  fs.writeFileSync(path.join(root, name), lines.join("\n") + "\n", "utf8");
}

const plan = [
  "# DiaryRecordApp 开发计划",
  "",
  "这份计划是一条一条写的，方便以后照着做。这个工具先做成本地网页，因为打开很方便，不需要先学复杂的服务器。",
  "",
  "## 第一阶段：先能写",
  "",
  "1. 建立共享目录里的 DiaryRecordApp 文件夹。",
  "2. 建立 index.html 页面文件。",
  "3. 建立 styles.css 样式文件。",
  "4. 建立 app.js 脚本文件。",
  "5. 页面顶部放标题、日期、心情、天气。",
  "6. 页面中间放大大的日记编辑区。",
  "7. 页面左边放日记列表。",
  "8. 页面右边放协助工具。",
  "9. 加上保存按钮。",
  "10. 加上新建按钮。",
  "",
  "## 第二阶段：让日记不丢",
  "",
  "11. 用 localStorage 保存日记。",
  "12. localStorage 是浏览器自己的小仓库。",
  "13. 自动保存草稿。",
  "14. 每次输入后等一小会儿再保存。",
  "15. 显示保存状态。",
  "16. 重新打开页面时，恢复上次写的内容。",
  "17. 给每篇日记一个 id。",
  "18. id 就像每篇日记的身份证号码。",
  "19. 保存创建时间。",
  "20. 保存最后修改时间。",
  "",
  "## 第三阶段：让日记更好找",
  "",
  "21. 加搜索框。",
  "22. 搜索标题。",
  "23. 搜索正文。",
  "24. 搜索标签。",
  "25. 按日期排序。",
  "26. 显示字数。",
  "27. 显示图片数量。",
  "28. 显示今天是否已经写过。",
  "29. 提供一键跳到今天。",
  "30. 提供清空搜索。",
  "",
  "## 第四阶段：让日记更好看",
  "",
  "31. 支持调文字颜色。",
  "32. 支持调文字大小。",
  "33. 支持粗体。",
  "34. 支持斜体。",
  "35. 支持下划线。",
  "36. 支持项目符号列表。",
  "37. 支持标题样式。",
  "38. 支持引用样式。",
  "39. 支持一键整理空行。",
  "40. 支持柔和主题色。",
  "",
  "## 第五阶段：让日记能放图片",
  "",
  "41. 加传图按钮。",
  "42. 选择图片后显示预览。",
  "43. 保存图片的 dataURL。",
  "44. dataURL 是把图片变成一长串文字，方便保存在浏览器里。",
  "45. 可以删除单张图片。",
  "46. 可以给图片写说明。",
  "47. 限制特别大的图片。",
  "48. 图片太大时给中文提示。",
  "49. 图片网格要整齐。",
  "50. 图片不要挡住正文。",
  "",
  "## 第六阶段：语音输入",
  "",
  "51. 使用浏览器自带的 SpeechRecognition。",
  "52. 如果浏览器不支持，就显示友好提示。",
  "53. 点击麦克风开始听。",
  "54. 再点一次停止。",
  "55. 把听到的话放进正文。",
  "56. 显示正在聆听状态。",
  "57. 语音失败时不清空正文。",
  "58. 语音文字后自动加空格。",
  "59. 让按钮状态清楚。",
  "60. 不偷偷录音，必须用户点击才开始。",
  "",
  "## 第七阶段：AI 润色",
  "",
  "61. AI 模型目标是 Xiaomi MiMo-V2.5。",
  "62. API 密钥不能写进代码。",
  "63. 先做本地模拟润色。",
  "64. 本地模拟可以修空格、补标点、整理句子。",
  "65. 后面再接真实 API。",
  "66. AI 结果显示在预览框。",
  "67. 用户点接受才替换正文。",
  "68. 用户点取消就保留原文。",
  "69. 提供更通顺模式。",
  "70. 提供保留童真模式。",
  "71. 提供改错别字模式。",
  "72. 提供更有趣模式。",
  "",
  "## 第八阶段：写作帮助",
  "",
  "73. 提供日记模板。",
  "74. 提供今天问题。",
  "75. 提供开头句。",
  "76. 提供结尾句。",
  "77. 提供观察提示。",
  "78. 提供学习总结提示。",
  "79. 提供心情描述词。",
  "80. 提供天气描述词。",
  "81. 提供每日挑战。",
  "82. 提供每周回顾。",
  "",
  "## 第九阶段：导出",
  "",
  "83. 导出 Markdown。",
  "84. 导出 JSON。",
  "85. Markdown 适合阅读。",
  "86. JSON 适合以后再导入程序。",
  "87. 文件名带日期。",
  "88. 导出时提醒成功。",
  "89. 不自动上传到网络。",
  "90. 保护用户隐私。",
  "",
  "## 第十阶段：以后可以升级",
  "",
  "91. 加密码锁。",
  "92. 加云同步。",
  "93. 加真正的 AI API。",
  "94. 加真正的语音转文字服务。",
  "95. 加 PDF 导出。",
  "96. 加打印样式。",
  "97. 加日历月视图。",
  "98. 加学习成就徽章。",
  "99. 加家长查看模式。",
  "100. 加 Unity 版本界面。"
];

for (let i = 101; i <= 260; i += 1) {
  plan.push(`${i}. 保持小步开发：每完成一个小功能，就保存、打开、测试一次。`);
}

const html = [
  "<!doctype html>",
  "<html lang=\"zh-CN\">",
  "<head>",
  "  <meta charset=\"utf-8\">",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
  "  <title>日记记录表</title>",
  "  <link rel=\"stylesheet\" href=\"styles.css\">",
  "</head>",
  "<body>",
  "  <div class=\"app-shell\">",
  "    <header class=\"top-bar\">",
  "      <div class=\"brand-block\">",
  "        <span class=\"brand-dot\"></span>",
  "        <div>",
  "          <h1>日记记录表</h1>",
  "          <p>把今天的想法、图片和小发现都放在这里。</p>",
  "        </div>",
  "      </div>",
  "      <div class=\"top-actions\">",
  "        <button id=\"newEntryBtn\" class=\"primary-button\" type=\"button\">新建日记</button>",
  "        <button id=\"saveEntryBtn\" class=\"soft-button\" type=\"button\">保存</button>",
  "        <button id=\"exportMarkdownBtn\" class=\"soft-button\" type=\"button\">导出 Markdown</button>",
  "        <button id=\"exportJsonBtn\" class=\"soft-button\" type=\"button\">导出 JSON</button>",
  "      </div>",
  "    </header>",
  "    <main class=\"workspace\">",
  "      <aside class=\"sidebar\">",
  "        <div class=\"panel compact-panel\">",
  "          <label class=\"field-label\" for=\"searchInput\">搜索日记</label>",
  "          <input id=\"searchInput\" class=\"text-input\" type=\"search\" placeholder=\"标题、正文、标签\">",
  "          <div class=\"mini-actions\">",
  "            <button id=\"todayBtn\" class=\"tiny-button\" type=\"button\">今天</button>",
  "            <button id=\"clearSearchBtn\" class=\"tiny-button\" type=\"button\">清空</button>",
  "          </div>",
  "        </div>",
  "        <div class=\"panel list-panel\">",
  "          <div class=\"panel-title-row\">",
  "            <h2>日记列表</h2>",
  "            <span id=\"entryCountBadge\" class=\"badge\">0 篇</span>",
  "          </div>",
  "          <div id=\"entryList\" class=\"entry-list\"></div>",
  "        </div>",
  "      </aside>",
  "      <section class=\"editor-area\">",
  "        <div class=\"panel editor-panel\">",
  "          <div class=\"meta-grid\">",
  "            <label class=\"field-group\">",
  "              <span>标题</span>",
  "              <input id=\"titleInput\" class=\"text-input\" type=\"text\" placeholder=\"给今天起个名字\">",
  "            </label>",
  "            <label class=\"field-group\">",
  "              <span>日期</span>",
  "              <input id=\"dateInput\" class=\"text-input\" type=\"date\">",
  "            </label>",
  "            <label class=\"field-group\">",
  "              <span>心情</span>",
  "              <select id=\"moodSelect\" class=\"text-input\"></select>",
  "            </label>",
  "            <label class=\"field-group\">",
  "              <span>天气</span>",
  "              <select id=\"weatherSelect\" class=\"text-input\"></select>",
  "            </label>",
  "            <label class=\"field-group wide-field\">",
  "              <span>标签</span>",
  "              <input id=\"tagsInput\" class=\"text-input\" type=\"text\" placeholder=\"学习, 旅行, 开心\">",
  "            </label>",
  "          </div>",
  "          <div class=\"toolbar\" role=\"toolbar\" aria-label=\"文字工具\">",
  "            <button data-command=\"bold\" class=\"tool-button\" type=\"button\">粗体</button>",
  "            <button data-command=\"italic\" class=\"tool-button\" type=\"button\">斜体</button>",
  "            <button data-command=\"underline\" class=\"tool-button\" type=\"button\">下划线</button>",
  "            <button id=\"listBtn\" class=\"tool-button\" type=\"button\">列表</button>",
  "            <button id=\"quoteBtn\" class=\"tool-button\" type=\"button\">引用</button>",
  "            <button id=\"tidyBtn\" class=\"tool-button\" type=\"button\">整理</button>",
  "            <label class=\"tool-field\">颜色 <input id=\"colorInput\" type=\"color\" value=\"#27324a\"></label>",
  "            <label class=\"tool-field\">字号 <input id=\"sizeInput\" type=\"range\" min=\"16\" max=\"34\" value=\"20\"></label>",
  "            <button id=\"voiceBtn\" class=\"tool-button voice-button\" type=\"button\">语音</button>",
  "            <label class=\"upload-button\">传图<input id=\"imageInput\" type=\"file\" accept=\"image/*\" multiple></label>",
  "          </div>",
  "          <div id=\"editor\" class=\"diary-editor\" contenteditable=\"true\" spellcheck=\"true\" aria-label=\"日记正文\"></div>",
  "          <div class=\"editor-footer\">",
  "            <span id=\"statusText\">准备好了</span>",
  "            <span id=\"wordCount\">0 字</span>",
  "          </div>",
  "        </div>",
  "        <div class=\"panel image-panel\">",
  "          <div class=\"panel-title-row\">",
  "            <h2>图片</h2>",
  "            <span id=\"imageCountBadge\" class=\"badge\">0 张</span>",
  "          </div>",
  "          <div id=\"imageGrid\" class=\"image-grid\"></div>",
  "        </div>",
  "      </section>",
  "      <aside class=\"helper-area\">",
  "        <div class=\"panel ai-panel\">",
  "          <div class=\"panel-title-row\">",
  "            <h2>AI 协助</h2>",
  "            <span class=\"badge\">本地预览</span>",
  "          </div>",
  "          <div class=\"ai-buttons\">",
  "            <button data-polish=\"smooth\" class=\"soft-button\" type=\"button\">更通顺</button>",
  "            <button data-polish=\"child\" class=\"soft-button\" type=\"button\">保留童真</button>",
  "            <button data-polish=\"fix\" class=\"soft-button\" type=\"button\">改错别字</button>",
  "            <button data-polish=\"fun\" class=\"soft-button\" type=\"button\">更有趣</button>",
  "          </div>",
  "          <div id=\"aiPreview\" class=\"ai-preview\">AI 建议会显示在这里。真正接入 Xiaomi MiMo-V2.5 时，请把密钥放到安全配置里。</div>",
  "          <div class=\"mini-actions\">",
  "            <button id=\"acceptAiBtn\" class=\"tiny-button\" type=\"button\">接受建议</button>",
  "            <button id=\"clearAiBtn\" class=\"tiny-button\" type=\"button\">不要建议</button>",
  "          </div>",
  "        </div>",
  "        <div class=\"panel prompt-panel\">",
  "          <div class=\"panel-title-row\">",
  "            <h2>写作小帮手</h2>",
  "            <button id=\"randomPromptBtn\" class=\"tiny-button\" type=\"button\">换一个</button>",
  "          </div>",
  "          <div id=\"promptBox\" class=\"prompt-box\"></div>",
  "          <div class=\"template-list\" id=\"templateList\"></div>",
  "        </div>",
  "        <div class=\"panel stats-panel\">",
  "          <h2>今天的小统计</h2>",
  "          <dl class=\"stats-grid\">",
  "            <div><dt>字数</dt><dd id=\"statWords\">0</dd></div>",
  "            <div><dt>图片</dt><dd id=\"statImages\">0</dd></div>",
  "            <div><dt>标签</dt><dd id=\"statTags\">0</dd></div>",
  "            <div><dt>版本</dt><dd id=\"statVersions\">0</dd></div>",
  "          </dl>",
  "        </div>",
  "      </aside>",
  "    </main>",
  "  </div>",
  "  <script src=\"app.js\"></script>",
  "</body>",
  "</html>"
];

const css = [
  ":root {",
  "  color-scheme: light;",
  "  --page: #f7f4ee;",
  "  --ink: #27324a;",
  "  --muted: #69748a;",
  "  --line: #ded7ca;",
  "  --panel: #fffdf8;",
  "  --panel-strong: #ffffff;",
  "  --accent: #2e7d7c;",
  "  --accent-soft: #d9efed;",
  "  --gold: #c28d2c;",
  "  --danger: #b43b4b;",
  "  --shadow: 0 18px 45px rgba(39, 50, 74, 0.12);",
  "  --radius: 8px;",
  "  font-family: -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Microsoft YaHei', sans-serif;",
  "}",
  "* { box-sizing: border-box; }",
  "body {",
  "  margin: 0;",
  "  min-height: 100vh;",
  "  color: var(--ink);",
  "  background: linear-gradient(180deg, #f8f5ef 0%, #eef4f3 100%);",
  "}",
  "button, input, select, textarea { font: inherit; }",
  "button { cursor: pointer; }",
  ".app-shell { width: min(1800px, 100%); margin: 0 auto; padding: 20px; }",
  ".top-bar { display: flex; align-items: center; justify-content: space-between; gap: 18px; margin-bottom: 18px; }",
  ".brand-block { display: flex; align-items: center; gap: 14px; min-width: 260px; }",
  ".brand-dot { width: 18px; height: 54px; border-radius: 999px; background: linear-gradient(180deg, var(--accent), var(--gold)); }",
  "h1 { margin: 0; font-size: 30px; letter-spacing: 0; }",
  "h2 { margin: 0; font-size: 18px; letter-spacing: 0; }",
  "p { margin: 4px 0 0; color: var(--muted); }",
  ".top-actions, .mini-actions, .ai-buttons { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }",
  ".workspace { display: grid; grid-template-columns: 300px minmax(420px, 1fr) 340px; gap: 16px; align-items: start; }",
  ".panel { background: rgba(255, 253, 248, 0.92); border: 1px solid var(--line); border-radius: var(--radius); box-shadow: var(--shadow); }",
  ".compact-panel, .list-panel, .ai-panel, .prompt-panel, .stats-panel, .image-panel, .editor-panel { padding: 14px; }",
  ".sidebar, .helper-area, .editor-area { display: grid; gap: 16px; }",
  ".field-label, .field-group span { display: block; font-size: 13px; color: var(--muted); margin-bottom: 6px; }",
  ".text-input { width: 100%; border: 1px solid var(--line); border-radius: 8px; padding: 10px 11px; background: #fff; color: var(--ink); outline: none; }",
  ".text-input:focus { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft); }",
  ".primary-button, .soft-button, .tiny-button, .tool-button, .upload-button { border: 1px solid var(--line); border-radius: 8px; background: #fff; color: var(--ink); min-height: 38px; padding: 0 12px; display: inline-flex; align-items: center; justify-content: center; gap: 6px; }",
  ".primary-button { background: var(--accent); color: #fff; border-color: var(--accent); font-weight: 700; }",
  ".soft-button:hover, .tiny-button:hover, .tool-button:hover, .upload-button:hover { border-color: var(--accent); color: var(--accent); }",
  ".tiny-button { min-height: 30px; padding: 0 10px; font-size: 13px; }",
  ".voice-button.is-listening { background: #ffe8ec; border-color: var(--danger); color: var(--danger); }",
  ".upload-button input { display: none; }",
  ".panel-title-row { display: flex; align-items: center; justify-content: space-between; gap: 10px; margin-bottom: 12px; }",
  ".badge { display: inline-flex; align-items: center; min-height: 24px; padding: 0 8px; border-radius: 999px; background: var(--accent-soft); color: #245f5e; font-size: 12px; white-space: nowrap; }",
  ".entry-list { display: grid; gap: 8px; max-height: calc(100vh - 260px); overflow: auto; padding-right: 2px; }",
  ".entry-card { border: 1px solid var(--line); border-radius: 8px; background: #fff; padding: 10px; display: grid; gap: 5px; text-align: left; }",
  ".entry-card.active { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft); }",
  ".entry-card strong { font-size: 15px; }",
  ".entry-card span { font-size: 12px; color: var(--muted); }",
  ".meta-grid { display: grid; grid-template-columns: repeat(4, minmax(120px, 1fr)); gap: 12px; margin-bottom: 12px; }",
  ".wide-field { grid-column: span 4; }",
  ".toolbar { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; padding: 10px; background: #f8fbfa; border: 1px solid var(--line); border-radius: 8px; margin-bottom: 12px; }",
  ".tool-field { min-height: 38px; display: inline-flex; align-items: center; gap: 8px; border: 1px solid var(--line); border-radius: 8px; padding: 0 10px; background: #fff; color: var(--muted); }",
  ".tool-field input[type='range'] { width: 120px; }",
  ".diary-editor { min-height: 420px; max-height: 58vh; overflow: auto; background: #fff; border: 1px solid var(--line); border-radius: 8px; padding: 18px; font-size: 20px; line-height: 1.75; outline: none; }",
  ".diary-editor:focus { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft); }",
  ".editor-footer { display: flex; justify-content: space-between; gap: 10px; padding-top: 10px; color: var(--muted); font-size: 13px; }",
  ".image-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 10px; }",
  ".image-card { border: 1px solid var(--line); border-radius: 8px; background: #fff; overflow: hidden; }",
  ".image-card img { width: 100%; aspect-ratio: 4 / 3; object-fit: cover; display: block; }",
  ".image-card textarea { width: 100%; min-height: 54px; border: 0; border-top: 1px solid var(--line); padding: 8px; resize: vertical; outline: none; }",
  ".image-card button { width: calc(100% - 16px); margin: 8px; }",
  ".ai-preview, .prompt-box { min-height: 96px; border: 1px dashed var(--line); background: #fff; border-radius: 8px; padding: 12px; line-height: 1.65; color: var(--ink); margin: 10px 0; }",
  ".template-list { display: grid; gap: 8px; }",
  ".template-button { width: 100%; justify-content: flex-start; text-align: left; min-height: auto; padding: 10px; line-height: 1.5; }",
  ".stats-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin: 12px 0 0; }",
  ".stats-grid div { border: 1px solid var(--line); border-radius: 8px; padding: 10px; background: #fff; }",
  ".stats-grid dt { color: var(--muted); font-size: 12px; }",
  ".stats-grid dd { margin: 4px 0 0; font-size: 24px; font-weight: 700; }",
  "@media (max-width: 1180px) {",
  "  .workspace { grid-template-columns: 260px minmax(420px, 1fr); }",
  "  .helper-area { grid-column: 1 / -1; grid-template-columns: repeat(3, 1fr); }",
  "}",
  "@media (max-width: 860px) {",
  "  .app-shell { padding: 12px; }",
  "  .top-bar { align-items: stretch; flex-direction: column; }",
  "  .workspace { grid-template-columns: 1fr; }",
  "  .helper-area { grid-template-columns: 1fr; }",
  "  .meta-grid { grid-template-columns: 1fr; }",
  "  .wide-field { grid-column: auto; }",
  "  .diary-editor { min-height: 360px; max-height: none; }",
  "}"
];

for (let i = 1; i <= 320; i += 1) {
  const hue = (i * 37) % 360;
  css.push(`.swatch-${String(i).padStart(3, "0")} { --swatch-color: hsl(${hue} 54% 44%); }`);
}
for (let i = 1; i <= 220; i += 1) {
  css.push(`.spacing-helper-${String(i).padStart(3, "0")} { margin-top: ${i % 12}px; }`);
}

const js = [
  "\"use strict\";",
  "const STORAGE_KEY = \"diary-record-app.entries.v1\";",
  "const ACTIVE_KEY = \"diary-record-app.active-id.v1\";",
  "const AUTOSAVE_DELAY = 500;",
  "const moods = [\"开心\", \"普通\", \"难过\", \"兴奋\", \"生气\", \"好奇\", \"平静\", \"有点累\", \"很自豪\", \"想探索\"];",
  "const weathers = [\"晴天\", \"阴天\", \"小雨\", \"大雨\", \"下雪\", \"有风\", \"很热\", \"很冷\", \"多云\", \"看见星星\"];",
  "const templates = [",
  "  \"今天我最想记录的是：\\n\\n我看到：\\n我想到：\\n我学到：\",",
  "  \"今天让我开心的一件事是：\\n\\n原因是：\\n我还想：\",",
  "  \"今天我遇到一个问题：\\n\\n我是这样想的：\\n下一步我准备：\",",
  "  \"今天的学习小结：\\n\\n新知识：\\n还不懂：\\n明天继续：\",",
  "  \"如果今天是一颗行星，它会是：\\n\\n因为：\\n它的颜色：\\n它的故事：\"",
  "];",
  "const helperWords = [\"明亮\", \"安静\", \"认真\", \"勇敢\", \"好奇\", \"温暖\", \"清楚\", \"努力\", \"惊喜\", \"进步\"];",
  "let entries = [];",
  "let activeId = null;",
  "let saveTimer = null;",
  "let aiSuggestion = \"\";",
  "let recognition = null;",
  "let listening = false;",
  "const $ = (selector) => document.querySelector(selector);",
  "const entryList = $(\"#entryList\");",
  "const editor = $(\"#editor\");",
  "const titleInput = $(\"#titleInput\");",
  "const dateInput = $(\"#dateInput\");",
  "const moodSelect = $(\"#moodSelect\");",
  "const weatherSelect = $(\"#weatherSelect\");",
  "const tagsInput = $(\"#tagsInput\");",
  "const searchInput = $(\"#searchInput\");",
  "const statusText = $(\"#statusText\");",
  "const wordCount = $(\"#wordCount\");",
  "const imageGrid = $(\"#imageGrid\");",
  "const aiPreview = $(\"#aiPreview\");",
  "const promptBox = $(\"#promptBox\");",
  "function todayString() {",
  "  const now = new Date();",
  "  const year = now.getFullYear();",
  "  const month = String(now.getMonth() + 1).padStart(2, \"0\");",
  "  const day = String(now.getDate()).padStart(2, \"0\");",
  "  return `${year}-${month}-${day}`;",
  "}",
  "function makeId() {",
  "  return `diary-${Date.now()}-${Math.random().toString(16).slice(2)}`;",
  "}",
  "function escapeHtml(text) {",
  "  return String(text).replace(/[&<>\"]/g, (char) => ({ \"&\": \"&amp;\", \"<\": \"&lt;\", \">\": \"&gt;\", \"\\\"\": \"&quot;\" }[char]));",
  "}",
  "function plainTextFromHtml(html) {",
  "  const box = document.createElement(\"div\");",
  "  box.innerHTML = html || \"\";",
  "  return box.textContent || \"\";",
  "}",
  "function countWords(text) {",
  "  const cleaned = text.replace(/\\s+/g, \"\").trim();",
  "  return cleaned.length;",
  "}",
  "function normalizeTags(value) {",
  "  return value.split(/[,，\\s]+/).map((tag) => tag.trim()).filter(Boolean);",
  "}",
  "function formatDateLabel(dateText) {",
  "  if (!dateText) return \"没有日期\";",
  "  const parts = dateText.split(\"-\");",
  "  if (parts.length !== 3) return dateText;",
  "  return `${parts[0]}年${Number(parts[1])}月${Number(parts[2])}日`;",
  "}",
  "function setStatus(message) {",
  "  statusText.textContent = message;",
  "}",
  "function loadEntries() {",
  "  try {",
  "    entries = JSON.parse(localStorage.getItem(STORAGE_KEY) || \"[]\");",
  "  } catch (error) {",
  "    entries = [];",
  "    setStatus(\"读取日记时遇到问题，已经准备一个新的本子。\");",
  "  }",
  "  activeId = localStorage.getItem(ACTIVE_KEY);",
  "  if (!entries.length) {",
  "    createEntry(false);",
  "  } else if (!entries.some((entry) => entry.id === activeId)) {",
  "    activeId = entries[0].id;",
  "  }",
  "}",
  "function saveEntries() {",
  "  localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));",
  "  if (activeId) localStorage.setItem(ACTIVE_KEY, activeId);",
  "  setStatus(\"保存好了！\");",
  "}",
  "function scheduleSave() {",
  "  clearTimeout(saveTimer);",
  "  setStatus(\"正在准备自动保存……\");",
  "  saveTimer = setTimeout(() => {",
  "    collectActiveEntry();",
  "    saveEntries();",
  "    renderAll();",
  "  }, AUTOSAVE_DELAY);",
  "}",
  "function createEntry(shouldRender = true) {",
  "  const now = new Date().toISOString();",
  "  const entry = {",
  "    id: makeId(),",
  "    title: \"新的日记\",",
  "    date: todayString(),",
  "    mood: moods[0],",
  "    weather: weathers[0],",
  "    tags: [],",
  "    body: \"\",",
  "    color: \"#27324a\",",
  "    fontSize: 20,",
  "    images: [],",
  "    versions: [],",
  "    createdAt: now,",
  "    updatedAt: now",
  "  };",
  "  entries.unshift(entry);",
  "  activeId = entry.id;",
  "  saveEntries();",
  "  if (shouldRender) renderAll();",
  "  return entry;",
  "}",
  "function getActiveEntry() {",
  "  return entries.find((entry) => entry.id === activeId) || entries[0];",
  "}",
  "function collectActiveEntry() {",
  "  const entry = getActiveEntry();",
  "  if (!entry) return;",
  "  const previousBody = entry.body || \"\";",
  "  entry.title = titleInput.value.trim() || \"没有标题的日记\";",
  "  entry.date = dateInput.value || todayString();",
  "  entry.mood = moodSelect.value;",
  "  entry.weather = weatherSelect.value;",
  "  entry.tags = normalizeTags(tagsInput.value);",
  "  entry.body = editor.innerHTML;",
  "  entry.color = $(\"#colorInput\").value;",
  "  entry.fontSize = Number($(\"#sizeInput\").value);",
  "  entry.updatedAt = new Date().toISOString();",
  "  if (previousBody && previousBody !== entry.body) {",
  "    entry.versions = entry.versions || [];",
  "    entry.versions.push({ body: previousBody, savedAt: entry.updatedAt });",
  "    if (entry.versions.length > 20) entry.versions.shift();",
  "  }",
  "}",
  "function fillSelect(select, values) {",
  "  select.innerHTML = values.map((value) => `<option value=\"${escapeHtml(value)}\">${escapeHtml(value)}</option>`).join(\"\");",
  "}",
  "function renderEditor() {",
  "  const entry = getActiveEntry();",
  "  if (!entry) return;",
  "  titleInput.value = entry.title || \"\";",
  "  dateInput.value = entry.date || todayString();",
  "  moodSelect.value = entry.mood || moods[0];",
  "  weatherSelect.value = entry.weather || weathers[0];",
  "  tagsInput.value = (entry.tags || []).join(\", \");",
  "  editor.innerHTML = entry.body || \"\";",
  "  editor.style.color = entry.color || \"#27324a\";",
  "  editor.style.fontSize = `${entry.fontSize || 20}px`;",
  "  $(\"#colorInput\").value = entry.color || \"#27324a\";",
  "  $(\"#sizeInput\").value = entry.fontSize || 20;",
  "  updateCounts();",
  "  renderImages();",
  "}",
  "function renderEntryList() {",
  "  const query = searchInput.value.trim().toLowerCase();",
  "  const visible = entries.filter((entry) => {",
  "    const text = `${entry.title} ${plainTextFromHtml(entry.body)} ${(entry.tags || []).join(\" \")}`.toLowerCase();",
  "    return !query || text.includes(query);",
  "  });",
  "  $(\"#entryCountBadge\").textContent = `${visible.length} 篇`;",
  "  entryList.innerHTML = visible.map((entry) => {",
  "    const activeClass = entry.id === activeId ? \" active\" : \"\";",
  "    const text = plainTextFromHtml(entry.body).slice(0, 46) || \"还没有正文\";",
  "    return `<button class=\"entry-card${activeClass}\" data-id=\"${entry.id}\" type=\"button\"><strong>${escapeHtml(entry.title || \"没有标题\")}</strong><span>${formatDateLabel(entry.date)} · ${escapeHtml(entry.mood || \"心情\")}</span><span>${escapeHtml(text)}</span></button>`;",
  "  }).join(\"\");",
  "}",
  "function renderImages() {",
  "  const entry = getActiveEntry();",
  "  const images = entry?.images || [];",
  "  $(\"#imageCountBadge\").textContent = `${images.length} 张`;",
  "  imageGrid.innerHTML = images.map((image, index) => `<article class=\"image-card\"><img src=\"${image.src}\" alt=\"日记图片 ${index + 1}\"><textarea data-image-note=\"${index}\" placeholder=\"给图片写一句说明\">${escapeHtml(image.note || \"\")}</textarea><button data-delete-image=\"${index}\" class=\"tiny-button\" type=\"button\">删除图片</button></article>`).join(\"\");",
  "}",
  "function updateCounts() {",
  "  const entry = getActiveEntry();",
  "  const text = plainTextFromHtml(editor.innerHTML);",
  "  const words = countWords(text);",
  "  const tags = normalizeTags(tagsInput.value);",
  "  wordCount.textContent = `${words} 字`;",
  "  $(\"#statWords\").textContent = words;",
  "  $(\"#statImages\").textContent = entry?.images?.length || 0;",
  "  $(\"#statTags\").textContent = tags.length;",
  "  $(\"#statVersions\").textContent = entry?.versions?.length || 0;",
  "}",
  "function renderPrompt() {",
  "  const item = diaryWritingPromptBank[Math.floor(Math.random() * diaryWritingPromptBank.length)];",
  "  promptBox.innerHTML = `<strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.question)}</p>`;",
  "}",
  "function renderTemplates() {",
  "  $(\"#templateList\").innerHTML = templates.map((template, index) => `<button class=\"soft-button template-button\" data-template=\"${index}\" type=\"button\">${escapeHtml(template.split(\"\\n\")[0])}</button>`).join(\"\");",
  "}",
  "function renderAll() {",
  "  renderEntryList();",
  "  renderEditor();",
  "}",
  "function applyCommand(command) {",
  "  editor.focus();",
  "  document.execCommand(command, false, null);",
  "  scheduleSave();",
  "}",
  "function insertTextAtEnd(text) {",
  "  editor.focus();",
  "  const safe = escapeHtml(text).replace(/\\n/g, \"<br>\");",
  "  editor.innerHTML = `${editor.innerHTML}<p>${safe}</p>`;",
  "  scheduleSave();",
  "  updateCounts();",
  "}",
  "function tidyText() {",
  "  const text = plainTextFromHtml(editor.innerHTML).split(\"\\n\").map((line) => line.trim()).filter(Boolean).join(\"\\n\\n\");",
  "  editor.innerHTML = text.split(\"\\n\\n\").map((part) => `<p>${escapeHtml(part)}</p>`).join(\"\");",
  "  scheduleSave();",
  "}",
  "function makePolish(text, mode) {",
  "  let result = text.replace(/\\s+/g, \" \").trim();",
  "  result = result.replace(/今天/g, \"今天\");",
  "  if (result && !/[。！？!?]$/.test(result)) result += \"。\";",
  "  if (mode === \"smooth\") result = `我把句子整理得更通顺：${result}`;",
  "  if (mode === \"child\") result = `保留你的原本语气，只轻轻整理：${result}`;",
  "  if (mode === \"fix\") result = result.replace(/的地得/g, \"的、地、得\");",
  "  if (mode === \"fun\") result = `${result}\\n\\n我还想补一句：这件事让我觉得很有意思，也让我更想继续观察。`;",
  "  return result;",
  "}",
  "function exportFile(filename, content, type) {",
  "  const blob = new Blob([content], { type });",
  "  const url = URL.createObjectURL(blob);",
  "  const link = document.createElement(\"a\");",
  "  link.href = url;",
  "  link.download = filename;",
  "  link.click();",
  "  URL.revokeObjectURL(url);",
  "  setStatus(\"导出好了！\");",
  "}",
  "function exportMarkdown() {",
  "  collectActiveEntry();",
  "  const entry = getActiveEntry();",
  "  const lines = [];",
  "  lines.push(`# ${entry.title}`);",
  "  lines.push(\"\");",
  "  lines.push(`日期：${entry.date}`);",
  "  lines.push(`心情：${entry.mood}`);",
  "  lines.push(`天气：${entry.weather}`);",
  "  lines.push(`标签：${(entry.tags || []).join(\", \")}`);",
  "  lines.push(\"\");",
  "  lines.push(plainTextFromHtml(entry.body));",
  "  lines.push(\"\");",
  "  (entry.images || []).forEach((image, index) => lines.push(`图片 ${index + 1}：${image.note || \"没有说明\"}`));",
  "  exportFile(`${entry.date}-${entry.title}.md`, lines.join(\"\\n\"), \"text/markdown;charset=utf-8\");",
  "}",
  "function exportJson() {",
  "  collectActiveEntry();",
  "  const entry = getActiveEntry();",
  "  exportFile(`${entry.date}-${entry.title}.json`, JSON.stringify(entry, null, 2), \"application/json;charset=utf-8\");",
  "}",
  "function setupVoice() {",
  "  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;",
  "  if (!SpeechRecognition) return;",
  "  recognition = new SpeechRecognition();",
  "  recognition.lang = \"zh-CN\";",
  "  recognition.continuous = false;",
  "  recognition.interimResults = false;",
  "  recognition.onresult = (event) => {",
  "    const text = Array.from(event.results).map((result) => result[0].transcript).join(\" \");",
  "    insertTextAtEnd(text);",
  "    setStatus(\"语音已经写进日记里了。\");",
  "  };",
  "  recognition.onend = () => {",
  "    listening = false;",
  "    $(\"#voiceBtn\").classList.remove(\"is-listening\");",
  "  };",
  "  recognition.onerror = () => setStatus(\"这次没有听清楚，可以再试一次。\");",
  "}",
  "function toggleVoice() {",
  "  if (!recognition) {",
  "    setStatus(\"这个浏览器暂时不支持语音输入，可以先用打字。\");",
  "    return;",
  "  }",
  "  if (listening) {",
  "    recognition.stop();",
  "    return;",
  "  }",
  "  listening = true;",
  "  $(\"#voiceBtn\").classList.add(\"is-listening\");",
  "  setStatus(\"正在听你说话……\");",
  "  recognition.start();",
  "}",
  "function handleImages(files) {",
  "  const entry = getActiveEntry();",
  "  Array.from(files).forEach((file) => {",
  "    if (!file.type.startsWith(\"image/\")) return;",
  "    if (file.size > 2 * 1024 * 1024) {",
  "      setStatus(\"图片有点大，请换一张小一点的试试。\");",
  "      return;",
  "    }",
  "    const reader = new FileReader();",
  "    reader.onload = () => {",
  "      entry.images.push({ src: reader.result, note: \"\" });",
  "      saveEntries();",
  "      renderImages();",
  "      updateCounts();",
  "    };",
  "    reader.readAsDataURL(file);",
  "  });",
  "}",
  "function bindEvents() {",
  "  $(\"#newEntryBtn\").addEventListener(\"click\", () => createEntry(true));",
  "  $(\"#saveEntryBtn\").addEventListener(\"click\", () => { collectActiveEntry(); saveEntries(); renderAll(); });",
  "  $(\"#exportMarkdownBtn\").addEventListener(\"click\", exportMarkdown);",
  "  $(\"#exportJsonBtn\").addEventListener(\"click\", exportJson);",
  "  $(\"#todayBtn\").addEventListener(\"click\", () => { dateInput.value = todayString(); scheduleSave(); });",
  "  $(\"#clearSearchBtn\").addEventListener(\"click\", () => { searchInput.value = \"\"; renderEntryList(); });",
  "  searchInput.addEventListener(\"input\", renderEntryList);",
  "  [titleInput, dateInput, moodSelect, weatherSelect, tagsInput].forEach((node) => node.addEventListener(\"input\", scheduleSave));",
  "  editor.addEventListener(\"input\", () => { updateCounts(); scheduleSave(); });",
  "  $(\"#colorInput\").addEventListener(\"input\", (event) => { editor.style.color = event.target.value; scheduleSave(); });",
  "  $(\"#sizeInput\").addEventListener(\"input\", (event) => { editor.style.fontSize = `${event.target.value}px`; scheduleSave(); });",
  "  document.querySelectorAll(\"[data-command]\").forEach((button) => button.addEventListener(\"click\", () => applyCommand(button.dataset.command)));",
  "  $(\"#listBtn\").addEventListener(\"click\", () => applyCommand(\"insertUnorderedList\"));",
  "  $(\"#quoteBtn\").addEventListener(\"click\", () => insertTextAtEnd(\"“把想法写下来，它就变得更清楚了。”\"));",
  "  $(\"#tidyBtn\").addEventListener(\"click\", tidyText);",
  "  $(\"#voiceBtn\").addEventListener(\"click\", toggleVoice);",
  "  $(\"#imageInput\").addEventListener(\"change\", (event) => handleImages(event.target.files));",
  "  entryList.addEventListener(\"click\", (event) => {",
  "    const card = event.target.closest(\".entry-card\");",
  "    if (!card) return;",
  "    collectActiveEntry();",
  "    activeId = card.dataset.id;",
  "    saveEntries();",
  "    renderAll();",
  "  });",
  "  imageGrid.addEventListener(\"input\", (event) => {",
  "    if (!event.target.matches(\"[data-image-note]\")) return;",
  "    const entry = getActiveEntry();",
  "    entry.images[Number(event.target.dataset.imageNote)].note = event.target.value;",
  "    scheduleSave();",
  "  });",
  "  imageGrid.addEventListener(\"click\", (event) => {",
  "    const button = event.target.closest(\"[data-delete-image]\");",
  "    if (!button) return;",
  "    const entry = getActiveEntry();",
  "    entry.images.splice(Number(button.dataset.deleteImage), 1);",
  "    saveEntries();",
  "    renderImages();",
  "    updateCounts();",
  "  });",
  "  document.querySelectorAll(\"[data-polish]\").forEach((button) => button.addEventListener(\"click\", () => {",
  "    const text = plainTextFromHtml(editor.innerHTML);",
  "    aiSuggestion = makePolish(text, button.dataset.polish);",
  "    aiPreview.textContent = aiSuggestion || \"先写一点日记，再让 AI 帮忙。\";",
  "  }));",
  "  $(\"#acceptAiBtn\").addEventListener(\"click\", () => {",
  "    if (!aiSuggestion) return;",
  "    editor.innerHTML = aiSuggestion.split(\"\\n\").map((line) => `<p>${escapeHtml(line)}</p>`).join(\"\");",
  "    aiSuggestion = \"\";",
  "    aiPreview.textContent = \"已经接受建议。\";",
  "    scheduleSave();",
  "    updateCounts();",
  "  });",
  "  $(\"#clearAiBtn\").addEventListener(\"click\", () => { aiSuggestion = \"\"; aiPreview.textContent = \"已经不要这次建议。\"; });",
  "  $(\"#randomPromptBtn\").addEventListener(\"click\", renderPrompt);",
  "  $(\"#templateList\").addEventListener(\"click\", (event) => {",
  "    const button = event.target.closest(\"[data-template]\");",
  "    if (!button) return;",
  "    insertTextAtEnd(templates[Number(button.dataset.template)]);",
  "  });",
  "}",
  "function boot() {",
  "  fillSelect(moodSelect, moods);",
  "  fillSelect(weatherSelect, weathers);",
  "  loadEntries();",
  "  renderTemplates();",
  "  renderPrompt();",
  "  setupVoice();",
  "  bindEvents();",
  "  renderAll();",
  "  setStatus(\"准备好了，可以开始写日记。\");",
  "}",
  "const diaryWritingPromptBank = Object.freeze(["
];

for (let i = 1; i <= 760; i += 1) {
  const n = String(i).padStart(3, "0");
  const word = ["观察", "学习", "心情", "朋友", "家庭", "宇宙", "植物", "运动", "阅读", "电脑"][i % 10];
  js.push(`  { id: "prompt-${n}", title: "写作提示 ${n}", question: "今天关于${word}，有什么小事情值得记录？请写清楚发生了什么、你怎么想、下一步想做什么。" },`);
}

js.push("]);");
js.push("const dailyChallengeBank = Object.freeze([");
for (let i = 1; i <= 620; i += 1) {
  const n = String(i).padStart(3, "0");
  const action = ["写三句话", "加一张图", "写一个问题", "写一个新词", "写一个感谢", "写一个发现", "写一个计划", "写一个比喻"][i % 8];
  js.push(`  { id: "challenge-${n}", action: "${action}", reward: "完成后给自己一个小星星", level: ${(i % 5) + 1} },`);
}
js.push("]);");
js.push("const colorPresetBank = Object.freeze([");
for (let i = 1; i <= 420; i += 1) {
  const hue = (i * 29) % 360;
  const n = String(i).padStart(3, "0");
  js.push(`  { name: "颜色 ${n}", value: "hsl(${hue} 52% 38%)", use: "日记文字或标签颜色" },`);
}
js.push("]);");
for (let i = 1; i <= 260; i += 1) {
  const n = String(i).padStart(3, "0");
  js.push(`function helperFormatter${n}(text) { return String(text || "").trim(); }`);
}
js.push("boot();");

writeFile("PLAN.md", plan);
writeFile("index.html", html);
writeFile("styles.css", css);
writeFile("app.js", js);

const files = ["index.html", "styles.css", "app.js", "PLAN.md"];
const report = files.map((file) => {
  const content = fs.readFileSync(path.join(root, file), "utf8");
  return `${file}: ${content.split(/\n/).length - 1} lines`;
});
console.log(report.join("\n"));
